const fs = require('fs');
const path = require('path');
const id = Math.floor(Math.random() * 1000);

/* 
First path.join is the original name of the file you want to change 
Second path.join is what the new name of the file will be (random ID generated by Math.floor) 
*/ 


const rename = () => {
  for (let i = 1000; i <= 1000; i++) {
    fs.rename(
      path.join(__dirname, '/files', 'test.csv'), // original file goes here
      path.join(__dirname, '/files', `test-${id}.csv`), // new file with id variable goes here
      (e) => {
        if (e) throw e;
        console.log('File Renamed 😀');
      }
    );
  }
};

const renameOtherFile = () => {
  for (let i = 1000; i <= 1000; i++) {
    fs.rename(
      path.join(__dirname, '/files', 'test-again.csv'), // original file goes here
      path.join(__dirname, '/files', `test-again-${id}.csv`), // new file with id variable goes here
      (e) => {
        if (e) throw e;
        console.log('File Renamed 😀');
      }
    );
  }
};

rename();
renameOtherFile();
